### PR TITLE
New ulmo release, v0.8.5. Create new conda packages

### PR DESCRIPTION
**Pull request by emiliom**
New release, version 0.8.5.
Note that 3 tests are known to be failing. That's ok, they're not fatal and we'll deal with them in a subsequent release.

Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered](https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by emiliom** [comment]
Circle-CI build failed, but conda-forge-linter is ok. Hmm.

This is my first time submitting a conda feedstock PR, for a package version update. This feedstock has been used before several times, though.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
These two steps were missing:

```
Reset the build number to 0 (if the version changed)
Re-rendered with the latest conda-smithy
```

and we need to update the checksum too. BTW, now we have a bot for PRs like these (See #11), so you don' have to worry about sending it, just merge the bot's PR.

**Comment by emiliom** [comment]
Thanks @ocefpaf !

I looked for a place to set the build number and couldn't find one; I figured the system would be smart enough to set it to 0 given that the version changed :wink: But I see now that there are instructions about that in https://github.com/conda-forge/ulmo-feedstock/blob/master/README.md

> we need to update the checksum too. 

Do I still need to do that, or is it done?

> BTW, now we have a bot for PRs like these (See #11), so you don' have to worry about sending it, just merge the bot's PR.

Ok. I followed the instructions in https://github.com/conda-forge/ulmo-feedstock/blob/master/README.md. Are they out of date?

Last but not least, I see there's only one 0.8.5 file on the conda-forge channel at https://anaconda.org/conda-forge/ulmo, though the icon shows all 3 OS's. I'm used to seeing different files for the different OS's. I assume this is a new (for me) conda approach?

**Comment by ocefpaf** [comment]
> Do I still need to do that, or is it done?

Nope. I did it and merge the PR.

> Ok. I followed the instructions in /README.md@master. Are they out of date?

No really. Some people still want to send manual PRs or sometimes the URL changes and the bot won't pick up the updated. However, most of the time just wait 1-2 hours after a release before sending a PR b/c the bot will probably do it for you and save you time.

> Last but not least, I see there's only one 0.8.5 file on the conda-forge channel at anaconda.org/conda-forge/ulmo, though the icon shows all 3 OS's. I'm used to seeing different files for the different OS's. I assume this is a new (for me) conda approach?

`ulmo` is `noarch` now, that package can be installed in any platform/python.

**Comment by emiliom** [comment]
Great, thanks!

**Pull request merged**
