### PR TITLE
update recipe for version 0.8.4

### PR DESCRIPTION
**Pull request by dharhas**

### CODE REVIEW

**Comment by dharhas** [comment]
@ocefpaf can you look at this. The failures on OS X seems to be conda-forge related, it seems to have failed on installing conda. If I'm looking at it right it looks like the windows py27 failure is also related to finding the miniconda executable.

Also TravisCI has this warning message:  "This job was configured to run on an OS X image that was retired on January 20, 2017. It was routed to our Xcode 6.4 infrastructure."

**Comment by ocefpaf** [comment]
@dharhas re-rendering should fix that. (The URL to download miniconda changed from  `http` to `https`,but there are many other updates to the feedstock with latest `conda-smithy`.)

**Comment by dharhas** [comment]
@ocefpaf Can I trigger a re-render (and how) or do one of the conda-forge admins need to do that?

**Comment by ocefpaf** [comment]
> @ocefpaf Can I trigger a re-render (and how) or do one of the conda-forge admins need to do that?

Sorry. Should've send you how to do it. The bot will do it eventually, but we can force re-rendering with `conda-smithy`:

```
conda create -n _SMITHY -c conda-forge conda-smithy
source activate _SMITHY
conda smithy rerender
```

(You can try putting it in your root env, but I recommend to isolate it into a special `_` named env.)

**Pull request merged**
